version: "3.7"

services:
  app:
    build: 
      context: ./app
      args:
        user: leandro
        uid: 1000
    ports:
      - 9000:9000
    working_dir: /var/www/html
    volumes:
      - ./html:/var/www/html
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 1010
      MYSQL_DB: laravel
    links:
      - mysql
    networks:
      - bridge

  mysql:
    image: mysql:8.0.22
    ports:
      - 33060:3306
    volumes:
      - ./mysql/mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 1010
      MYSQL_DATABASE: laravel
    networks:
      - bridge

  web:
    image: nginx:1.19-alpine
    environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
    ports:
      - 8000:80
    volumes:
      - ./html:/var/www/html
      - "./nginx/laravel.conf:/etc/nginx/conf.d/default.conf"
    links:
      - app
      - mysql
    networks:
      - bridge

networks: 
  bridge:
    driver: bridge
